sudo: required
dist: bionic

language: bash


script:
- chmod u+x bash DeployFroalaDemoApps.sh deploy
- echo "Done the deployement"


before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
