sudo: required
dist: bionic

language: bash


#script:
#- bash DeployFroalaDemoApps.sh deploy
#- echo "Done the deployement"


before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host {SERVER_IP}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

after_script:
- ssh -i ./deploy_key froala@10.220.201.231 cd /home/froala/travis/deploy && git pull origin master
- cd Froala-ransari-Test
- bash DeployFroalaDemoApps.sh deploy
- echo "Done the deployement"
